<a href="https://colab.research.google.com/github/Jungeey/Machine-Learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Introduction to NumPy**

What we will cover?


*   Creating arrays
*   Multidimensional array
*   Randomly generated arrays
*   Element wise Operations
*   Summarizing Operations




# Single Dimensional Array

In [ ]:
import numpy as np

In [ ]:
# Create an array with all value initialized with 0
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [ ]:
# Create an array with all value initialized with 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
# Create an array of size 10 with all elements 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
# Create an array with diifferent elements
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
# Create an array with range
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Create an array with evenly spaced numbers within a specified range
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multidimensional array

In [ ]:
# create an 3*3 array with all elements initialized with 0
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# create an 3*3 array with all elements initialized with 1
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# create an 3*3 array with elements 1 to 9
arr=np.array([[1, 2, 4],
          [4, 5, 6],
          [7, 8, 9]])
print(arr)

[[1 2 4]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Replacing array variable
arr[0][1]=20
print(arr)

[[ 1 20  4]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
# Replacing whole row with value 1
arr[2:]=1
print(arr)

[[ 1 20  4]
 [ 4  5  6]
 [ 1  1  1]]


In [ ]:
# Replacing whole Row
arr[:, 2]=[2,2,2]
print(arr)

[[ 1 20  2]
 [ 4  5  2]
 [ 1  1  2]]


In [ ]:
# Initializing array with all element value 1
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

# Randomly generated arrays

- NumPy can create arrays filled with random numbers.
- To ensure the reproducibility, you can seed ``` np.random.seed()``` . It will generate the exact same random numbers for each executions.
- If you rmremove or chnage the seed values, the sequence of random numbers will be changed.

In [ ]:
# Create an array with random elements
np.random.rand(5)

array([0.19894754, 0.8568503 , 0.35165264, 0.75464769, 0.29596171])

In [ ]:
# Using seed and creating array with random elements
np.random.seed(10)
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [ ]:
# Creating an 5*2 array with normal random
np.random.randn(5,2)

array([[-0.66437971, -0.60555494],
       [-0.65099088,  0.51256776],
       [ 0.26238882, -0.58273165],
       [ 1.36842193,  0.05336866],
       [ 1.49057364,  0.75636693]])

In [ ]:
# Picks random initeger from given range
np.random.randint(1,10)

9

In [ ]:
# Create an array of 5*2 with randomly generated element from given range
np.random.randint(low=0, high=100, size=(5,2))

array([[ 0, 18],
       [23,  3],
       [29, 16],
       [84, 82],
       [14, 51]])